[build]
  command = "npm run build"
  publish = "packages/frontend/.next"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
